version: '3.9'
services:
  main-service:
    container_name: main-service
    command: tail -f /dev/null #python main.py
    build:
      context: main_service
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: main-service
    env_file:
      - main_service/.environment
    volumes:
      - ./main_service:/code
    tty: true
    ports:
      - "5003:5003"

networks:
  default:
    external:
      name: core
